apiVersion: apps/v1

kind: Deployment

metadata:

  name: {{ include "student-app.fullname" . }}

spec:

  replicas: {{ .Values.replicaCount }}

  selector:

    matchLabels:

      app: student-app

  template:

    metadata:

      labels:

        app: student-app

    spec:

      containers:

      - name: student-app

        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"

        ports:

        - containerPort: 80
